server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}

rnis-service:
  scheduler-enable: ${RNIS_SERVICE_SCHEDULER_ENABLE:true}
  navigation-information-enable: ${RNIS_SERVICE_WITH_NAVIGATION_INFORMATION:false}
  object-info-pool-size: ${RNIS_SERVIEC_OBJECT_INFO_POOL_SIZE:50}
  hystrix-object-info-pool-size: ${RNIS_SERVICE_HYSTRIX_OBJECT_INFO_POOL_SIZE:100} # use more than object-info-pool-size
  hystrix-dashboard-url: /hystrix/monitor?stream=http://${server.address}:${server.port}/actuator/hystrix.stream

rnis:
  url: ${RNIS_URL:http://localhost:8081/}
  authentication:
    login: ${RNIS_AUTHENTICATION_LOGIN:user}
    password: ${RNIS_AUTHENTICATION_PASSWORD:password}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DB_NAME:rnis}?currentSchema=${DB_SCHEMA:rnis}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    default-schema: ${DB_SCHEMA:gkh-service}
    contexts: default
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO

open-api-info:
  name: @project.name@
  description: @project.description@
  build:
    version: @project.version@
    timestamp: @maven.build.timestamp@

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, hystrix.stream

hystrix:
  threadpool:
    objectInfoPool:
      coreSize: ${rnis-service.hystrix-object-info-pool-size}
  dashboard:
    proxy-stream-allow-list:
      - ${server.address}
  command:
    get object info from rnis:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: ${rnis-service.hystrix-object-info-pool-size}
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html