server:
  port: 8080
  address: localhost

spring:
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: utf-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, hystrix.stream

rnis-service:
  with-navigation-information: false
  object-info-pool-size: 50
  hystrix-dashboard-url: /hystrix/monitor?stream=http://${server.address}:${server.port}/actuator/hystrix.stream

hystrix:
  threadpool:
    objectInfoPool:
      coreSize: ${rnis-service.object-info-pool-size}
  dashboard:
    proxy-stream-allow-list:
      - ${server.address}
  command:
    get object info from rnis:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: ${rnis-service.object-info-pool-size}
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

rnis:
  url: http://localhost:8081/
  authentication:
    login: user
    password: password