hystrix:
  dashboard:
    proxy-stream-allow-list:
      - localhost
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, hystrix.stream

app:
  someservice:
    active: true

spring:
  data:
    rest:
      base-path: /datarest
      detection-strategy: annotated

  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true