spring:

  datasource:
    url: jdbc:h2:mem:testdb

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      #port: 0
      #database: test
      host: localhost
      port: 27017
      database: awesomeMongo

  h2:
    console:
      enabled: true

  batch:
    job:
      enabled: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    ROOT: ERROR