spring:
  data:
    mongodb:
      port: 0
      database: test
#      host: localhost
#      port: 27017
#      database: awesomeMongo

mongock:
  change-logs-scan-package:
    - ru.otus.homework11.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR